package com.xuhao.android.common.constant;
/*
 *  @项目名：  RootStartAuto
 *  @包名：    com.thinkrace.watchservice.orderlibrary
 *  @文件名:   OrderConstans
 *  @创建者:   win10
 *  @创建时间:  2018/5/10 17:12
 *  @描述：    TODO
 */

public class OrderConstans {

    public static final String BP00 = "BP00";//登录包
    public static final String BPLN = "BPLN";//登录包带IMSI
    public static final String BPLO = "BPLO";//C网设备登录包
    public static final String BPCM = "BPCM";//双向通话
    public static final String BP02 = "BP02";//多基站定位数据包
    public static final String BPFD = "BPFD";//交好友
    public static final String BP10 = "BP10";//报警与地址回复包
    public static final String BP03 = "BP03";//心跳包
    public static final String BP04 = "BP04";//低电量报警上报数据包
    public static final String BP05 = "BP05";//语音查询接收协议
    public static final String BP06 = "BP06";//AGPS辅助定位包
    public static final String BP73 = "BP73";//SOS报警
    public static final String BP39 = "BP39";//同步天气，空气，老黄历信息(拓展)
    public static final String BP49 = "BP49";//心率数据上传
    public static final String BP53 = "BP53";//通过基站校时协议
    public static final String BP54 = "BP54";//设备上报事件(解除绑定，步数获取)
    public static final String BP70 = "BP70";//表情消息上行
    public static final String BP86 = "BP86";//守护报警
    public static final String BPTM = "BPTM";//通过基站校时并获取经纬度协议
    public static final String BPHT = "BPHT";//上传心率与血压
    public static final String BPTQ = "BPTQ";//请求天气
    public static final String BP87 = "BP87";//请求设备二维码
    public static final String BP91 = "BP91";//睡眠数据上传
    public static final String BP01 = "BP01";

    /*下行*/
    public static final String BP11 = "BP11";   //设置主控号码
    public static final String BP12 = "BP12";   //设置SOS号码
    public static final String BP13 = "BP13";   //设置亲情号码
    public static final String BP14 = "BP14";   //设置联系人白名单
    public static final String BP15 = "BP15";   //GPRS定位数据上传时间间隔
    public static final String BP16 = "BP16";   //立即定位指令（长链接有效）
    public static final String BP17 = "BP17";   //恢复出厂设置
    public static final String BP18 = "BP18";   //重启终端
    public static final String BP19 = "BP19";   //设置服务器信息
    public static final String BP20 = "BP20";   //设置终端语言与时区
    public static final String BP21 = "BP21";   //设置计步器开关
    public static final String BP22 = "BP22";   //设置体感接听开关
    public static final String BP23 = "BP23";   //设置监听开关
    public static final String BP24 = "BP24";   //短信报警开关
    public static final String BP25 = "BP25";   //设置闹钟
    public static final String BP26 = "BP26";   //设置上课隐身时间段
    public static final String BP27 = "BP27";   //新语音记录提醒
    public static final String BP28 = "BP28";   //语音下行
    public static final String BP29 = "BP29";   //设置终端控制密码，非主控号短信指令需密码
    public static final String BP30 = "BP30";   //脱落报警开关
    public static final String BP31 = "BP31";   //关机指令
    public static final String BP32 = "BP32";   //拨打电话
    public static final String BP33 = "BP33";   //工作模式
    public static final String BP34 = "BP34";   //GPS工作时间段
    public static final String BP35 = "BP35";   //进入设备验证码显示界面
    public static final String BP36 = "BP36";   //进退出设备验证码显示界面
    public static final String BP37 = "BP37";   //设置休眠检测时间下行(拓展)
    public static final String BP38 = "BP38";   //设备休眠前主动上传休眠状态(拓展)
    public static final String BP40 = "BP40";   //文字下发(拓展)
    public static final String BP41 = "BP41";   //设置终端地址，紧急电话(拓展)
    public static final String BP43 = "BP43";   //奖励小红花
    public static final String BP44 = "BP44";   //休眠时间段
    public static final String BP45 = "BP45";   //静音开关
    public static final String BP46 = "BP46";   //立即拍照
    public static final String BP47 = "BP47";   //震动设置
    public static final String BP48 = "BP48";   //夜灯开关
    public static final String BP50 = "BP50";   //下发心跳检测指令
    public static final String BP52 = "BP52";   //删除电话本，单条
    public static final String BP55 = "BP55";   //设置蓝牙名称
    public static final String BP56 = "BP56";   //设置蓝牙开关
    public static final String BP57 = "BP57";   //设置带名称的SOS号码（3个）
    public static final String BP58 = "BP58";   //设置联系人白名单带关系和sos标志
    public static final String BP59 = "BP59";   //限制关机
    public static final String BP60 = "BP60";   //设置带名称亲情号码（3个）
    public static final String BP61 = "BP61";   //铃声设置
    public static final String BP62 = "BP62";   //铃声模式
    public static final String BP64 = "BP64";   //GPS工作时间段II
    public static final String BP65 = "BP65";   //音量设置
    public static final String BP66 = "BP66";   //屏幕亮度设置
    public static final String BP67 = "BP67";   //背景图片设置设置
    public static final String BP68 = "BP68";   //设备绑定、解绑通知
    public static final String BP69 = "BP69";   //表情下行消息
    public static final String BP71 = "BP71";   //奖励协议
    public static final String BP72 = "BP72";   //删除奖励协议
    public static final String BP75 = "BP75";   //设置闹钟(带名称)
    public static final String BP77 = "BP77";   //设置联系人带名称和头像
    public static final String BP78 = "BP78";   //查询话费
    public static final String BP79 = "BP79";   //设置定时开关机
    public static final String BPVL = "BPVL";   //带列表的新语音提醒
    public static final String BP80 = "BP80";   //设置WIFI安全守护
    public static final String BP81 = "BP81";   //设置自定义WIFI守护
    public static final String BP82 = "BP82";   //宠物追踪模式
    public static final String BPXL = "BPXL";   //测量心率
    public static final String BPXY = "BPXY";   //测量血压
    public static final String BPJZ = "BPJZ";   //血压校准
    public static final String BP83 = "BP83";   //设置联系人带名称和头像
    public static final String BP84 = "BP84";   //白名单开关
    public static final String BP85 = "BP85";   //设置闹钟(带类型)
    public static final String BP88 = "BP88";   //寻找设备
    public static final String BP89 = "BP89";   //灭屏时间设置
    public static final String BP90 = "BP90";   //上课隐身时间段(含单独开关)
    public static final String BP92 = "BP92";   //睡眠时间段设置
    public static final String BP93 = "BP93";   //设置城市生活号码（1个号码）
    public static final String BP94 = "BP94";   //通话音量设置
    public static final String BPDF = "BPDF";   //删除好友
    public static final String BP95 = "BP95";   //发送语音给好友上行
    public static final String BP96 = "BP96";   //发送语音给好友下行
    public static final String BP97 = "BP97";   //设置亲情号码（尊瑞6个）
    public static final String BPWL = "BPWL";   //设置联系人白名单（10个）

    public static final String AP11 = "AP11";   //设置主控号码
    public static final String AP12 = "AP12";   //设置SOS号码
    public static final String AP13 = "AP13";   //设置亲情号码
    public static final String AP14 = "AP14";   //设置联系人白名单
    public static final String AP15 = "AP15";   //GPRS定位数据上传时间间隔
    public static final String AP16 = "AP16";   //立即定位指令（长链接有效）
    public static final String AP17 = "AP17";   //恢复出厂设置
    public static final String AP18 = "AP18";   //重启终端
    public static final String AP19 = "AP19";   //设置服务器信息
    public static final String AP20 = "AP20";   //设置终端语言与时区
    public static final String AP21 = "AP21";   //设置计步器开关
    public static final String AP22 = "AP22";   //设置体感接听开关
    public static final String AP23 = "AP23";   //设置监听开关
    public static final String AP24 = "AP24";   //短信报警开关
    public static final String AP25 = "AP25";   //设置闹钟
    public static final String AP26 = "AP26";   //设置上课隐身时间段
    public static final String AP27 = "AP27";   //新语音记录提醒
    public static final String AP28 = "AP28";   //语音下行
    public static final String AP29 = "AP29";   //设置终端控制密码，非主控号短信指令需密码
    public static final String AP30 = "AP30";   //脱落报警开关
    public static final String AP31 = "AP31";   //关机指令
    public static final String AP32 = "AP32";   //拨打电话
    public static final String AP33 = "AP33";   //工作模式
    public static final String AP34 = "AP34";   //GPS工作时间段
    public static final String AP35 = "AP35";   //进入设备验证码显示界面
    public static final String AP36 = "AP36";   //进退出设备验证码显示界面
    public static final String AP37 = "AP37";   //设置休眠检测时间下行(拓展)
    public static final String AP38 = "AP38";   //设备休眠前主动上传休眠状态(拓展)
    public static final String AP40 = "AP40";   //文字下发(拓展)
    public static final String AP41 = "AP41";   //设置终端地址，紧急电话(拓展)
    public static final String AP43 = "AP43";   //奖励小红花
    public static final String AP44 = "AP44";   //休眠时间段
    public static final String AP45 = "AP45";   //静音开关
    public static final String AP46 = "AP46";   //立即拍照
    public static final String AP47 = "AP47";   //震动设置
    public static final String AP48 = "AP48";   //夜灯开关
    public static final String AP50 = "AP50";   //下发心跳检测指令
    public static final String AP51 = "AP51";   //下发电话本，单条
    public static final String AP52 = "AP52";   //删除电话本，单条
    public static final String AP55 = "AP55";   //设置蓝牙名称
    public static final String AP56 = "AP56";   //设置蓝牙开关
    public static final String AP57 = "AP57";   //设置带名称的SOS号码（3个）
    public static final String AP58 = "AP58";   //设置联系人白名单带关系和sos标志
    public static final String AP59 = "AP59";   //限制关机
    public static final String AP60 = "AP60";   //设置带名称亲情号码（3个）
    public static final String AP61 = "AP61";   //铃声设置
    public static final String AP62 = "AP62";   //铃声模式
    public static final String AP64 = "AP64";   //GPS工作时间段II
    public static final String AP65 = "AP65";   //音量设置
    public static final String AP66 = "AP66";   //屏幕亮度设置
    public static final String AP67 = "AP67";   //背景图片设置设置
    public static final String AP68 = "AP68";   //设备绑定、解绑通知
    public static final String AP69 = "AP69";   //表情下行消息
    public static final String AP71 = "AP71";   //奖励协议
    public static final String AP72 = "AP72";   //删除奖励协议
    public static final String AP75 = "AP75";   //设置闹钟(带名称)
    public static final String AP77 = "AP77";   //设置联系人带名称和头像
    public static final String AP78 = "AP78";   //查询话费
    public static final String AP79 = "AP79";   //设置定时开关机
    public static final String APVL = "APVL";   //带列表的新语音提醒
    public static final String AP80 = "AP80";   //设置WIFI安全守护
    public static final String AP81 = "AP81";   //设置自定义WIFI守护
    public static final String AP82 = "AP82";   //宠物追踪模式
    public static final String APXL = "APXL";   //测量心率
    public static final String APXY = "APXY";   //测量血压
    public static final String APJZ = "APJZ";   //血压校准
    public static final String AP83 = "AP83";   //设置联系人带名称和头像
    public static final String AP84 = "AP84";   //白名单开关
    public static final String AP85 = "AP85";   //设置闹钟(带类型)
    public static final String AP88 = "AP88";   //寻找设备
    public static final String AP89 = "AP89";   //灭屏时间设置
    public static final String AP90 = "AP90";   //上课隐身时间段(含单独开关)
    public static final String AP92 = "AP92";   //睡眠时间段设置
    public static final String AP93 = "AP93";   //设置城市生活号码（1个号码）
    public static final String AP94 = "AP94";   //通话音量设置
    public static final String APDF = "APDF";   //删除好友
    public static final String AP95 = "AP95";   //语音上行发送给好友
    public static final String AP96 = "AP96";   //发送语音给好友下行
    public static final String AP97 = "AP97";   //设置亲情号码（尊瑞6个）
    public static final String APWL = "APWL";   //设置联系人白名单（10个）
    public static final String BPGL = "BPGL";   //下行监护人列表（10个）
    public static final String BPGF = "BPGF";   //下行设备围栏（App下行）
    public static final String BP98 = "BP98";   //运动步数目标设定

    public static final String BPPF = "BPPF";   //使用者信息下发
    public static final String BPVU = "BPVU";   //聊天以url方式下发文件连接
    public static final String BPNS = "BPNS";   //搜索手表附近wifi
    public static final String BPWS = "BPWS";   //设置手表连接wifi
    public static final String BPCD = "BPCD";   //单聊下发文字
    public static final String BPVR = "BPVR";   //录制视频并上传
    public static final String BPWK = "BPWK";   //保持设备活跃
}
